#include "stm32f0xx.h"

void initTimer3Chanel1withPwm (void)
{
	RCC->APB1ENR |= RCC_APB1ENR_TIM3EN;
	RCC->AHBENR  |= RCC_AHBENR_GPIOAEN;
	
	GPIOA->PUPDR |= 0x2000;
	
	GPIOA->MODER &= ~GPIO_MODER_MODER6;
	GPIOA->MODER |= GPIO_MODER_MODER6_1;
	
	GPIOA->AFR[0] |= 0x1 << 24;
	
	TIM3->PSC = 47;
	TIM3->ARR = 100;
	TIM3->CCR1 = 99;
	TIM3->CCMR1 |= TIM_CCMR1_OC1M_2 | TIM_CCMR1_OC1M_1 | TIM_CCMR1_OC1PE;
	TIM3->CCER |= TIM_CCER_CC1E;
	TIM3->BDTR |= TIM_BDTR_MOE;
	TIM3->CR1 |= TIM_CR1_CEN;
	TIM3->EGR  |= TIM_EGR_UG;
	
}
